/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProyectoFinal;

import ProyectoFinal.Views.Login;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Login login = new Login();
        login.setVisible(true);
        System.out.println(new App().getGreeting());
    }
}
